apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-tomcat-config
data:
  tomcat.conf: |
    upstream tomcat {
        ip_hash;
        server 172.17.20.100:8088;
    }
    server {
        listen  80;
        server_name 172.17.10.100;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;

                proxy_pass http://tomcat;
                proxy_redirect off;
                charset utf-8;
        }
    }
