apiVersion: apps/v1
kind: Deployment
metadata:                 # 3가지 필수 구성요소중 하나
  name: nginx           # 해당 이름으로 디플로이 먼트가 생성됨.
  labels:
    app: nginx
spec:                       # 3가지 필수 구성요서중 하나 specification, 나머지 하나는 status
  replicas: 2              # 2개의 리플리카 pod를 생성한다.
  selector:                # 디플로이먼트가 관리할 파드를 찾는 방법을 정의, matchLabels이 nginx인 파드를 디플로이먼트가 관리한다.
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx              # 파드는 .metadata.labels 필드를 사용 app: nginx 라는 레이블을 붙인다.
    spec:
      containers:
      - name: nginx            # 컨테이너 1개를 생성, .spec.template.spec.containers[0].name 필드를 사용해서 nginx 라는 이름을 붙인다.
        image: nginx:1.14.2  # 파드가 도커 허브의 nginx 1.14.2 버전 이미지를 실행하는 nginx 컨테이너 1개를 실행하는 것을 나타낸다.
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-config
      volumes:                  # 참고할 volume 지정
        - name: nginx-config    # volume 의 이름 지정
          configMap:
            name: nginx-tomcat-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  clusterIP: 172.17.10.100
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
